import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({results}) {
  console.log(results);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Are we loadshedding?</h1>
        <section id="loadshed">
          Eskom is currently loadshedding at Stage {results-1}
        </section>
      
    </>
  )
}

export async function getServerSideProps(){
  console.log('Hello from the server');

  const res = await fetch("https://loadshedding.eskom.co.za/LoadShedding/GetStatus")
  const data = await res.json();
  console.log(data);

  return {
    props: {
      results: data
    }
  }
}